/* Generated by tests/conformance/generate_firmware_header.py. */
#ifndef HEARTHBIT_CONFORMANCE_VECTORS_H
#define HEARTHBIT_CONFORMANCE_VECTORS_H

typedef struct {
    const char *id;
    const char *hex;
    bool valid;
} conformance_packet_vector_t;

static const conformance_packet_vector_t CONFORMANCE_PACKET_VECTORS[] = {
    {"packet.v1.message", "01020700000000000000010000030102030405060708616263", true},
    {"packet.v1.raw_deflate", "010107000000000000000104000d010203040506070800b46360646266616518522400", true},
    {"packet.v1.zlib_read", "0101070000000000000001040013010203040506070800b4789c63606462666165185224009dbc01c3", true},
    {"packet.invalid.version", "03020700000000000000010000030102030405060708616263", false},
    {"packet.invalid.header_truncated", "010207", false},
    {"packet.invalid.payload_truncated", "01020700000000000000010000040102030405060708616263", false},
    {"packet.invalid.signature_truncated", "01020700000000000000010200000102030405060708", false},
    {"packet.invalid.padding", "010207000000000000000100000301020304050607086162630203", false},
    {"packet.invalid.deflate_truncated", "010107000000000000000104000c010203040506070800b463606462666165185224", false},
    {"packet.invalid.deflate_trailing", "010107000000000000000104000e010203040506070800b4636064626661651852240058", false},
    {"packet.invalid.expanded_size", "010107000000000000000104000d010203040506070800b36360646266616518522400", false},
};

#define CONFORMANCE_PACKET_VECTOR_COUNT \
    (sizeof(CONFORMANCE_PACKET_VECTORS) / sizeof(CONFORMANCE_PACKET_VECTORS[0]))

#endif
